#!/bin/bash

. ./common
   

echo "Fetching ..."
scp -A $launcherNode:~/Runner/Launcher/AllOutputs.txt RemoteAllOutputs.txt
scp -A $launcherNode:~/Runner/Launcher/AllResults.txt RemoteAllResults.txt
scp -A $launcherNode:~/Runner/Launcher/LauncherOutput.txt RemoteLauncherOutput.txt
cat RemoteAllResults.txt


